apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://salaarasim345_db_user:rWnXRyIEaMHmS4Kb@cluster0.xdtckpg.mongodb.net/baatcheet?retryWrites=true&w=majority"
  JWT_SECRET: "your_jwt_secret_key"
  CLOUDINARY_CLOUD_NAME: "ddf85fmrf"
  CLOUDINARY_API_KEY: "766957716777719"
  CLOUDINARY_API_SECRET: "qcgX7PShSjwxpccnZKeRyN3OFBU"
  ARCJET_API_KEY: "ajkey_01k53yh9xmeyfrv6gk84bxhxrj"
  ARCJET_ENV: "development"
